### ISSUE TITLE
Allow tipping users not yet known the bot

### ISSUE THREAD

**Issue by abrkn** [abrkn/tipmebch#22]

**Comment by tea-spoon** [comment]
This sounds important :) @chaintip

**Comment by chaintip** [comment]
`0.00431444 BCH`| `~   4.99 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4x0vc2cwc0y2sfk2tu8tme32j06ckakmhkhf) to this issue by @tea-spoon.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/19), get a pull request merged with ```@chaintip fixes #22``` in the creation comment.

**Comment by hjvogel** [comment]
Thats awsome! Tx and watching ;)

**Comment by tea-spoon** [comment]
Thanks! Not sure why @abrkn closed this issue. Is it fixed already?

**Comment by supermamon** [comment]
@tea-spoon, looks like @abrkn fixed it himself (see #23). Wonder if @chaintip handles such case.

**Comment by tea-spoon** [comment]
@supermamon, He could have claimed it by merging a pull request from a branch he created that fixes this issue. I'm cautious to send the bounty to the closer of the issue because there could be a lot of other reasons that the issue got closed in addition to it being fixed by the owner.

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/19), get a pull request merged with ```@chaintip fixes #22``` in the creation comment.
