### ISSUE TITLE
Block stake to get access to a chat

### ISSUE THREAD

**Issue by HostFat** [abrkn/tipmebch#34]
Example: To get access to @randombchchat, the user has to block 0.001 BCH. (this amound should be set by the admin of the @randombchchat)
So, if the user wants to get access to @randombchchat, he will have to deposit 0.0001 BCH, and send a command like this to the bot:
user: stakeaccess @randombchchat
bot: Do you want to block 0.0001 BCH to get access to @randombchchat? [YES] [NO]

Then, the user can join to the chat.
If the user try to access to the @randombchchat without blocking the 0.001 BCH he will instantly banned by the bot, until he blocks the right amount.

After this, the user wont be able to unlock (and withdraw) the 0.0001 BCH from the bot until he is on the @randombchchat (or he can do it but the bot will instantly ban him)

There could be even other solutions, as sending an amount (maybe 0.0001 BCH) as fee to the miner.
The bot should do this, and then giving to the user the access to the chat.

**Comment by abrkn** [comment]
Why not make another bot that utilizes TipMeBch for this? This way we get bots-all-the-way and TipMeBch has less feature creep.
